"""baseline schema

Revision ID: 376ee87d4a9d
Revises: 
Create Date: 2026-08-26 07:08:22.583708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376ee87d4a9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('territory_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'terminated', name='partnerstatusenum'), nullable=False),
    sa.Column('tier', sa.Enum('explorer', 'builder', 'elite', name='partnertierenum'), nullable=False),
    sa.Column('security_deposit_paid', sa.Boolean(), nullable=False),
    sa.Column('security_deposit_amount', sa.Float(), nullable=False),
    sa.Column('agreement_start_date', sa.DateTime(), nullable=True),
    sa.Column('agreement_end_date', sa.DateTime(), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('default_unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.Enum('pos', 'scale', 'vision', 'manual', name='providertypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_key'), 'providers', ['key'], unique=True)
    op.create_index(op.f('ix_providers_provider_type'), 'providers', ['provider_type'], unique=False)
    op.create_table('zone_heatmap_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_hour', sa.DateTime(), nullable=False),
    sa.Column('zone_occupancy', sa.JSON(), nullable=False),
    sa.Column('peak_zone_id', sa.String(length=36), nullable=False),
    sa.Column('total_transitions', sa.Integer(), nullable=False),
    sa.Column('hygiene_breach_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heatmap_outlet_hour', 'zone_heatmap_snapshots', ['outlet_id', 'snapshot_hour'], unique=False)
    op.create_index(op.f('ix_zone_heatmap_snapshots_outlet_id'), 'zone_heatmap_snapshots', ['outlet_id'], unique=False)
    op.create_table('zone_occupancy_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('chef_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zone_occ_outlet_ts', 'zone_occupancy_events', ['outlet_id', 'entered_at'], unique=False)
    op.create_index(op.f('ix_zone_occupancy_events_entered_at'), 'zone_occupancy_events', ['entered_at'], unique=False)
    op.create_index(op.f('ix_zone_occupancy_events_outlet_id'), 'zone_occupancy_events', ['outlet_id'], unique=False)
    op.create_table('zone_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('chef_id', sa.String(length=36), nullable=True),
    sa.Column('from_zone_id', sa.String(length=36), nullable=False),
    sa.Column('to_zone_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('had_wash_basin_visit', sa.Boolean(), nullable=False),
    sa.Column('is_hygiene_breach', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_transitions_outlet_id'), 'zone_transitions', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_zone_transitions_timestamp'), 'zone_transitions', ['timestamp'], unique=False)
    op.create_table('partner_revenue_statements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_billing', sa.Float(), nullable=False),
    sa.Column('partner_share', sa.Float(), nullable=False),
    sa.Column('replate_share', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('utr_number', sa.String(length=50), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_revenue_statements_partner_id'), 'partner_revenue_statements', ['partner_id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fssai_number', sa.String(length=50), nullable=False),
    sa.Column('cuisine_type', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_partner_id'), 'restaurants', ['partner_id'], unique=False)
    op.create_table('outlets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('plan', sa.Enum('starter', 'pro', 'enterprise', name='planenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('go_live_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlets_restaurant_id'), 'outlets', ['restaurant_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'replate_team', 'partner', 'restaurant_owner', 'restaurant_manager', name='userroleenum'), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('restaurant_id', sa.String(length=36), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_profiles_clerk_id'), 'user_profiles', ['clerk_id'], unique=True)
    op.create_table('camera_streams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stream_type', sa.String(length=10), nullable=False),
    sa.Column('stream_url_encrypted', sa.Text(), nullable=True),
    sa.Column('username_encrypted', sa.String(length=512), nullable=True),
    sa.Column('password_encrypted', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_streams_outlet_id'), 'camera_streams', ['outlet_id'], unique=False)
    op.create_table('dishes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_outlet_id'), 'dishes', ['outlet_id'], unique=False)
    op.create_table('edge_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=False),
    sa.Column('cpu_temp_celsius', sa.Float(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_edge_devices_outlet_id'), 'edge_devices', ['outlet_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost_inr', sa.Float(), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('reorder_level', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_outlet_id'), 'inventory_items', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_product_id'), 'inventory_items', ['product_id'], unique=False)
    op.create_index('ix_inventory_outlet_product', 'inventory_items', ['outlet_id', 'product_id'], unique=True)
    op.create_table('layout_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('what_data_shows', sa.Text(), nullable=False),
    sa.Column('estimated_impact', sa.Text(), nullable=False),
    sa.Column('estimated_monthly_saving_inr', sa.Integer(), nullable=True),
    sa.Column('fssai_risk', sa.Text(), nullable=True),
    sa.Column('fixes', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layout_recommendations_outlet_id'), 'layout_recommendations', ['outlet_id'], unique=False)
    op.create_table('people_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('pos', 'scale', 'vision', 'manual', name='providertypeenum'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('person_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_events_occurred_at'), 'people_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_people_events_outlet_id'), 'people_events', ['outlet_id'], unique=False)
    op.create_index('ix_people_outlet_ts', 'people_events', ['outlet_id', 'occurred_at'], unique=False)
    op.create_table('profit_impact_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('revenue_inr', sa.Float(), nullable=False),
    sa.Column('cogs_theoretical_inr', sa.Float(), nullable=False),
    sa.Column('cogs_actual_inr', sa.Float(), nullable=False),
    sa.Column('waste_cost_inr', sa.Float(), nullable=False),
    sa.Column('leakage_cost_inr', sa.Float(), nullable=False),
    sa.Column('portion_cost_inr', sa.Float(), nullable=False),
    sa.Column('total_variance_cost_inr', sa.Float(), nullable=False),
    sa.Column('margin_erosion_percent', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_impact_snapshots_outlet_id'), 'profit_impact_snapshots', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_profit_impact_snapshots_period_date'), 'profit_impact_snapshots', ['period_date'], unique=False)
    op.create_index('ix_profit_outlet_date', 'profit_impact_snapshots', ['outlet_id', 'period_date'], unique=True)
    op.create_table('raw_ingest_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('pos', 'scale', 'vision', 'manual', name='providertypeenum'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_ingest_events_outlet_id'), 'raw_ingest_events', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_raw_ingest_events_received_at'), 'raw_ingest_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_ingest_events_source_provider'), 'raw_ingest_events', ['source_provider'], unique=False)
    op.create_index(op.f('ix_raw_ingest_events_source_type'), 'raw_ingest_events', ['source_type'], unique=False)
    op.create_index('ix_raw_ingest_outlet_type_ts', 'raw_ingest_events', ['outlet_id', 'source_type', 'received_at'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('badge_photo_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_outlet_id'), 'staff', ['outlet_id'], unique=False)
    op.create_table('compliance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('chef_id', sa.String(length=36), nullable=False),
    sa.Column('chef_name', sa.String(length=255), nullable=False),
    sa.Column('dish_id', sa.String(length=36), nullable=False),
    sa.Column('dish_name', sa.String(length=255), nullable=False),
    sa.Column('sop_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('step_name', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.Enum('step_pass', 'step_fail', 'step_late', 'step_skip', 'hygiene_breach', 'ingredient_error', 'plating_deviation', 'timing_violation', name='eventtypeenum'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='severityenum'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('video_clip_url', sa.String(length=512), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_events_chef_id'), 'compliance_events', ['chef_id'], unique=False)
    op.create_index(op.f('ix_compliance_events_outlet_id'), 'compliance_events', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_compliance_events_timestamp'), 'compliance_events', ['timestamp'], unique=False)
    op.create_index('ix_compliance_outlet_ts', 'compliance_events', ['outlet_id', 'timestamp'], unique=False)
    op.create_table('consumption_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('theoretical_qty', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source_breakdown', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consumption_outlet_item_date', 'consumption_records', ['outlet_id', 'item_id', 'period_date'], unique=True)
    op.create_index(op.f('ix_consumption_records_item_id'), 'consumption_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_consumption_records_outlet_id'), 'consumption_records', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_consumption_records_period_date'), 'consumption_records', ['period_date'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('txn_type', sa.Enum('purchase', 'consumption', 'waste', 'adjustment', 'count', name='inventorytxntypeenum'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost_inr', sa.Float(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('pos', 'scale', 'vision', 'manual', name='providertypeenum'), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('dish_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_txn_outlet_item_ts', 'inventory_transactions', ['outlet_id', 'item_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_item_id'), 'inventory_transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_occurred_at'), 'inventory_transactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_outlet_id'), 'inventory_transactions', ['outlet_id'], unique=False)
    op.create_table('kitchen_zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('polygon_points', sa.JSON(), nullable=False),
    sa.Column('is_hygiene_sensitive', sa.Boolean(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.Column('fssai_zone_class', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_streams.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_zones_outlet_id'), 'kitchen_zones', ['outlet_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dish_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_per_serving', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_dish_product', 'recipe_ingredients', ['dish_id', 'product_id'], unique=True)
    op.create_index(op.f('ix_recipe_ingredients_dish_id'), 'recipe_ingredients', ['dish_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_product_id'), 'recipe_ingredients', ['product_id'], unique=False)
    op.create_table('sop_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('dish_id', sa.String(length=36), nullable=False),
    sa.Column('dish_name', sa.String(length=255), nullable=False),
    sa.Column('recorded_by', sa.String(length=255), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=False),
    sa.Column('video_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('lock_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'annotating', 'review', 'locked', name='sopstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sop_outlet_dish', 'sop_records', ['outlet_id', 'dish_id'], unique=False)
    op.create_index(op.f('ix_sop_records_outlet_id'), 'sop_records', ['outlet_id'], unique=False)
    op.create_table('training_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chef_id', sa.String(length=36), nullable=False),
    sa.Column('chef_name', sa.String(length=255), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('module_type', sa.Enum('micro_video', 'checklist', 'quiz', 'shadow_session', 'team_briefing', name='moduletypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_step_id', sa.String(length=36), nullable=True),
    sa.Column('source_clip_url', sa.String(length=512), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('generated_by', sa.String(length=10), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_modules_chef_id'), 'training_modules', ['chef_id'], unique=False)
    op.create_index(op.f('ix_training_modules_outlet_id'), 'training_modules', ['outlet_id'], unique=False)
    op.create_table('variance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('dish_id', sa.String(length=36), nullable=True),
    sa.Column('variance_type', sa.Enum('waste', 'leakage', 'portion_control', name='variancetypeenum'), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('expected_qty', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=False),
    sa.Column('variance_qty', sa.Float(), nullable=False),
    sa.Column('variance_percent', sa.Float(), nullable=False),
    sa.Column('cost_impact_inr', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewed', 'resolved', name='variancestatusenum'), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_variance_outlet_type_date', 'variance_records', ['outlet_id', 'variance_type', 'period_date'], unique=False)
    op.create_index(op.f('ix_variance_records_item_id'), 'variance_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_variance_records_outlet_id'), 'variance_records', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_variance_records_period_date'), 'variance_records', ['period_date'], unique=False)
    op.create_index(op.f('ix_variance_records_variance_type'), 'variance_records', ['variance_type'], unique=False)
    op.create_table('sop_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sop_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_timestamp_sec', sa.Float(), nullable=False),
    sa.Column('end_timestamp_sec', sa.Float(), nullable=False),
    sa.Column('allowed_duration_min_sec', sa.Float(), nullable=False),
    sa.Column('allowed_duration_max_sec', sa.Float(), nullable=False),
    sa.Column('required_ingredients', sa.JSON(), nullable=False),
    sa.Column('visual_checkpoint', sa.Text(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('can_be_skipped', sa.Boolean(), nullable=False),
    sa.Column('reference_frame_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['sop_id'], ['sop_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_steps_sop_id'), 'sop_steps', ['sop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sop_steps_sop_id'), table_name='sop_steps')
    op.drop_table('sop_steps')
    op.drop_index(op.f('ix_variance_records_variance_type'), table_name='variance_records')
    op.drop_index(op.f('ix_variance_records_period_date'), table_name='variance_records')
    op.drop_index(op.f('ix_variance_records_outlet_id'), table_name='variance_records')
    op.drop_index(op.f('ix_variance_records_item_id'), table_name='variance_records')
    op.drop_index('ix_variance_outlet_type_date', table_name='variance_records')
    op.drop_table('variance_records')
    op.drop_index(op.f('ix_training_modules_outlet_id'), table_name='training_modules')
    op.drop_index(op.f('ix_training_modules_chef_id'), table_name='training_modules')
    op.drop_table('training_modules')
    op.drop_index(op.f('ix_sop_records_outlet_id'), table_name='sop_records')
    op.drop_index('ix_sop_outlet_dish', table_name='sop_records')
    op.drop_table('sop_records')
    op.drop_index(op.f('ix_recipe_ingredients_product_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_dish_id'), table_name='recipe_ingredients')
    op.drop_index('ix_recipe_dish_product', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_kitchen_zones_outlet_id'), table_name='kitchen_zones')
    op.drop_table('kitchen_zones')
    op.drop_index(op.f('ix_inventory_transactions_outlet_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_occurred_at'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_item_id'), table_name='inventory_transactions')
    op.drop_index('ix_inv_txn_outlet_item_ts', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_consumption_records_period_date'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_outlet_id'), table_name='consumption_records')
    op.drop_index(op.f('ix_consumption_records_item_id'), table_name='consumption_records')
    op.drop_index('ix_consumption_outlet_item_date', table_name='consumption_records')
    op.drop_table('consumption_records')
    op.drop_index('ix_compliance_outlet_ts', table_name='compliance_events')
    op.drop_index(op.f('ix_compliance_events_timestamp'), table_name='compliance_events')
    op.drop_index(op.f('ix_compliance_events_outlet_id'), table_name='compliance_events')
    op.drop_index(op.f('ix_compliance_events_chef_id'), table_name='compliance_events')
    op.drop_table('compliance_events')
    op.drop_index(op.f('ix_staff_outlet_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index('ix_raw_ingest_outlet_type_ts', table_name='raw_ingest_events')
    op.drop_index(op.f('ix_raw_ingest_events_source_type'), table_name='raw_ingest_events')
    op.drop_index(op.f('ix_raw_ingest_events_source_provider'), table_name='raw_ingest_events')
    op.drop_index(op.f('ix_raw_ingest_events_received_at'), table_name='raw_ingest_events')
    op.drop_index(op.f('ix_raw_ingest_events_outlet_id'), table_name='raw_ingest_events')
    op.drop_table('raw_ingest_events')
    op.drop_index('ix_profit_outlet_date', table_name='profit_impact_snapshots')
    op.drop_index(op.f('ix_profit_impact_snapshots_period_date'), table_name='profit_impact_snapshots')
    op.drop_index(op.f('ix_profit_impact_snapshots_outlet_id'), table_name='profit_impact_snapshots')
    op.drop_table('profit_impact_snapshots')
    op.drop_index('ix_people_outlet_ts', table_name='people_events')
    op.drop_index(op.f('ix_people_events_outlet_id'), table_name='people_events')
    op.drop_index(op.f('ix_people_events_occurred_at'), table_name='people_events')
    op.drop_table('people_events')
    op.drop_index(op.f('ix_layout_recommendations_outlet_id'), table_name='layout_recommendations')
    op.drop_table('layout_recommendations')
    op.drop_index('ix_inventory_outlet_product', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_product_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_outlet_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_edge_devices_outlet_id'), table_name='edge_devices')
    op.drop_table('edge_devices')
    op.drop_index(op.f('ix_dishes_outlet_id'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_camera_streams_outlet_id'), table_name='camera_streams')
    op.drop_table('camera_streams')
    op.drop_index(op.f('ix_user_profiles_clerk_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_outlets_restaurant_id'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_index(op.f('ix_restaurants_partner_id'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_partner_revenue_statements_partner_id'), table_name='partner_revenue_statements')
    op.drop_table('partner_revenue_statements')
    op.drop_index(op.f('ix_zone_transitions_timestamp'), table_name='zone_transitions')
    op.drop_index(op.f('ix_zone_transitions_outlet_id'), table_name='zone_transitions')
    op.drop_table('zone_transitions')
    op.drop_index(op.f('ix_zone_occupancy_events_outlet_id'), table_name='zone_occupancy_events')
    op.drop_index(op.f('ix_zone_occupancy_events_entered_at'), table_name='zone_occupancy_events')
    op.drop_index('ix_zone_occ_outlet_ts', table_name='zone_occupancy_events')
    op.drop_table('zone_occupancy_events')
    op.drop_index(op.f('ix_zone_heatmap_snapshots_outlet_id'), table_name='zone_heatmap_snapshots')
    op.drop_index('ix_heatmap_outlet_hour', table_name='zone_heatmap_snapshots')
    op.drop_table('zone_heatmap_snapshots')
    op.drop_index(op.f('ix_providers_provider_type'), table_name='providers')
    op.drop_index(op.f('ix_providers_key'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    op.drop_table('products')
    op.drop_table('partners')
    # ### end Alembic commands ###
